plugins:
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rspec
  - rubocop-capybara

AllCops:
  NewCops: enable
  DisplayStyleGuide: true
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'vendor/**/*'

Layout/LineLength:
  Exclude:
    - 'config/**/*'

Layout/FirstArgumentIndentation:
  EnforcedStyle: consistent

Lint/MissingSuper:
  Exclude:
    - 'app/components/**/*'
    - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'vendor/**/*'

Metrics/MethodLength:
  Max: 15

Naming/BlockForwarding:
  Enabled: false

Rails/DynamicFindBy:
  Whitelist:
    - find_by_token

Rails/I18nLocaleTexts:
  Enabled: false

Rails/UniqueValidationWithoutIndex:
  Exclude:
    - 'app/models/push_subscription.rb'

Style/ArgumentsForwarding:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DocumentationMethod:
  Enabled: true
  Include:
    - 'app/models/**/*.rb'
    - 'app/services/**/*.rb'
    - 'app/components/**/*.rb'
    - 'app/jobs/**/*.rb'
    - 'app/mailers/**/*.rb'

Style/HashSyntax:
  Enabled: false

Style/FetchEnvVar:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false
