AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'vendor/**/*'

Layout/LineLength:
  Exclude:
    - 'config/**/*'

Lint/MissingSuper:
  Exclude:
    - 'app/components/**/*'
    - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'vendor/**/*'

Metrics/MethodLength:
  Max: 15

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/FetchEnvVar:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
