require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/study_configs", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # StudyConfig. As you add validations to StudyConfig, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      StudyConfig.create! valid_attributes
      get study_configs_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      study_config = StudyConfig.create! valid_attributes
      get study_config_url(study_config)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_study_config_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      study_config = StudyConfig.create! valid_attributes
      get edit_study_config_url(study_config)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new StudyConfig" do
        expect {
          post study_configs_url, params: { study_config: valid_attributes }
        }.to change(StudyConfig, :count).by(1)
      end

      it "redirects to the created study_config" do
        post study_configs_url, params: { study_config: valid_attributes }
        expect(response).to redirect_to(study_config_url(StudyConfig.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new StudyConfig" do
        expect {
          post study_configs_url, params: { study_config: invalid_attributes }
        }.to change(StudyConfig, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post study_configs_url, params: { study_config: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested study_config" do
        study_config = StudyConfig.create! valid_attributes
        patch study_config_url(study_config), params: { study_config: new_attributes }
        study_config.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the study_config" do
        study_config = StudyConfig.create! valid_attributes
        patch study_config_url(study_config), params: { study_config: new_attributes }
        study_config.reload
        expect(response).to redirect_to(study_config_url(study_config))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        study_config = StudyConfig.create! valid_attributes
        patch study_config_url(study_config), params: { study_config: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested study_config" do
      study_config = StudyConfig.create! valid_attributes
      expect {
        delete study_config_url(study_config)
      }.to change(StudyConfig, :count).by(-1)
    end

    it "redirects to the study_configs list" do
      study_config = StudyConfig.create! valid_attributes
      delete study_config_url(study_config)
      expect(response).to redirect_to(study_configs_url)
    end
  end
end
