require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/terms", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Term. As you add validations to Term, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Term.create! valid_attributes
      get terms_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      term = Term.create! valid_attributes
      get term_url(term)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_term_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      term = Term.create! valid_attributes
      get edit_term_url(term)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Term" do
        expect {
          post terms_url, params: { term: valid_attributes }
        }.to change(Term, :count).by(1)
      end

      it "redirects to the created term" do
        post terms_url, params: { term: valid_attributes }
        expect(response).to redirect_to(term_url(Term.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Term" do
        expect {
          post terms_url, params: { term: invalid_attributes }
        }.to change(Term, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post terms_url, params: { term: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested term" do
        term = Term.create! valid_attributes
        patch term_url(term), params: { term: new_attributes }
        term.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the term" do
        term = Term.create! valid_attributes
        patch term_url(term), params: { term: new_attributes }
        term.reload
        expect(response).to redirect_to(term_url(term))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        term = Term.create! valid_attributes
        patch term_url(term), params: { term: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested term" do
      term = Term.create! valid_attributes
      expect {
        delete term_url(term)
      }.to change(Term, :count).by(-1)
    end

    it "redirects to the terms list" do
      term = Term.create! valid_attributes
      delete term_url(term)
      expect(response).to redirect_to(terms_url)
    end
  end
end
